# Generated by Django 3.1.7 on 2024-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex1',
            name='content',
        ),
        migrations.AddField(
            model_name='ex1',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ex1',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
