# Generated by Django 3.1.7 on 2024-06-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240618_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ex1',
            new_name='Booking',
        ),
    ]
