# Generated by Django 3.1.7 on 2024-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240619_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auteur',
            field=models.CharField(default='non référencé', max_length=128),
        ),
    ]
