# Generated by Django 3.1.7 on 2024-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_booking_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='published',
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
