# Generated by Django 3.1.7 on 2024-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240619_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
